### ISSUE TITLE
Project doesn't compile in m2e-core 2.4.0.20230704-0835

### ISSUE THREAD

**Issue by lrozenblyum** [eclipse-m2e/m2e-core#1474]
The sample project compiles in m2e-core 2.3.0 (and in command line mvn) and doesn't compile in the nightly build 2.4.0.20230704-0835. Eclipse 2023-06 is used.

See https://github.com/lrozenblyum/m2e-core-compilation-issue

The compilation error is issued for `First/src/main/java/com/leokom/Request.java` on the line 8
`The annotation @NotNull is disallowed for this location`

![изображение](https://github.com/eclipse-m2e/m2e-core/assets/1285898/bf86db53-58df-40ec-994d-c1ed934844f7)

Probably the transitive `validation-api` from the project `Second` somehow is applied here that's why the code cannot be compiled.
However the dependency tree shows correct information:

![изображение](https://github.com/eclipse-m2e/m2e-core/assets/1285898/bd956515-60ed-4df1-97dd-6bbac0bbbd67)

If we just remove the `validation-api` dependency from the `Second` project, the `First` project starts compiling.

**Comment by HannesWell** [comment]
Thank you for testing and reporting back.
If it now works, lets close this issue then. :)
